<a href="https://colab.research.google.com/github/gaurav700/DataScience-ML/blob/main/Numpy_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing numpy as np

In [ ]:
import numpy as np

In [ ]:
myarr = np.array([1,2,3,4,53,2,4,63,34], np.int8)

In [ ]:
myarr[3]

np.int8(4)

In [ ]:
myarr.shape

(9,)

In [ ]:
myarr.dtype

dtype('int8')

# Ways of creating array
*   Conversion from the other python structures (lists, tuples)
*   Intrinsic numpy array creation objects ( arange, ones, zeros)
*   Reading arrays from disk, either from standard or custom formats
*   Creating arrays from raw bytes through the use of string or buffers
*   Use of Special library function (random)



In [ ]:
#Creating using objects
listArray = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
listArray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# intrinsic numpy arrays creation
zeros = np.zeros((2,5))

In [ ]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
rng = np.arange(15)

In [ ]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
lspace = np.linspace(1,50,10)

In [ ]:
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [ ]:
empty = np.empty((4,6)) # will give a 4*6 array of random values

In [ ]:
empty

array([[-0.25, -0.5 ,  0.  , -0.25,  0.25, -0.5 ],
       [ 0.5 , -0.25,  0.25,  0.  ,  0.5 ,  0.25],
       [ 0.25,  0.5 ,  0.  ,  0.25, -0.25,  0.5 ],
       [-0.5 ,  0.25, -0.25,  0.  , -0.5 , -0.25]])

In [ ]:
iden = np.identity(5) # give a array of identity elements of n*n matrix

In [ ]:
iden

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Reshaping the array

In [ ]:
arr = np.arange(99)

In [ ]:
arr = arr.reshape(11, 9)

In [ ]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80],
       [81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98]])

# Reshaping to previous

In [ ]:
arr = arr.ravel()

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

# Numpy Axis

- 1D array has 1 axis
- 2D array has 3 axis [axis = 0, axis = 1]

In [ ]:
x = [[1,2,3], [4,5,6], [7,8,9]]
ar = np.array(x)
print(ar)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
ar.sum(axis=0)

array([12, 15, 18])

In [ ]:
ar.sum(axis=1)

array([ 6, 15, 24])

# Numpy array methods

In [ ]:
# transpose
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
# gives an iterator
for item in ar.flat:
  print(item)

1
2
3
4
5
6
7
8
9


In [ ]:
ar.ndim # gives the dimension of the array

2

In [ ]:
ar.size # gives the size of the array

9

In [ ]:
ar.nbytes # gives the total bytes consumed by the array

72

In [ ]:
oneDim = np.array([1,2,3,4,5,6,7,8,9,10])

In [ ]:
oneDim.argmax() # gives the index of the maximum element

np.int64(9)

In [ ]:
oneDim.argmin() # gives the index of minimum element

np.int64(0)

In [ ]:
oneDim.argsort() # gives the index of the sorted array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
ar.argmin(axis = 0) # gives the minimum element in all the rows

array([0, 0, 0])

In [ ]:
ar.argmax(axis = 1) # gives the maximum element in all the columns

array([2, 2, 2])

In [ ]:
ar1 = ar.argsort(axis = 1) # gives the index of the sorted array
ar1

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [ ]:
ar2 = ar.argsort(axis = 0)
ar2

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]])

In [ ]:
ar3 = ar1+ar2 # gives the addition result in an array
ar3

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [ ]:
ar4 = ar1*ar2 # gives the multiplication result in an array
ar4

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

In [ ]:
ar5 = ar1-ar2 # gives the subtration result in an array
ar5

array([[ 0,  1,  2],
       [-1,  0,  1],
       [-2, -1,  0]])

In [ ]:
ar6 = np.sqrt(ar4) # gives the square root of the array
ar6

array([[0.        , 0.        , 0.        ],
       [0.        , 1.        , 1.41421356],
       [0.        , 1.41421356, 2.        ]])

In [ ]:
ar6 = np.array(ar6)
ar6.ravel()  # gives the flattened array

array([0.        , 0.        , 0.        , 0.        , 1.        ,
       1.41421356, 0.        , 1.41421356, 2.        ])

In [ ]:
print(ar1)
np.where(ar1>1) # gives the index of the elements which are greater than 1

[[0 1 2]
 [0 1 2]
 [0 1 2]]


(array([0, 1, 2]), array([2, 2, 2]))

In [ ]:
np.count_nonzero(ar1) # gives the total number of non zero elements

6

In [ ]:
np.nonzero(ar1) # gives the index of the non zero elements

(array([0, 0, 1, 1, 2, 2]), array([1, 2, 1, 2, 1, 2]))